version: "3"
services:
  dev-db:
    image: mongo:3.6
    ports:
      - "27018:27017"
    volumes:
      - ./data/dev-db:/data/db
  test-db:
    image: mongo:3.6
    ports:
      - "27019:27017"
    volumes:
      - ./data/test-db:/data/db
