version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
      - image: circleci/mongo:3.6

    working_directory: ~/repo

    environment:
        # Needed to load the correct config
        NODE_ENV: circle
        PRODUCTION_BRANCH: master
        STAGING_BRANCH: develop

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: npm run lint

      - run:
          name: Run tests
          command: node node_modules/mocha/bin/mocha  test/test--index.js

      - run:
          name: Deploy to staging environment in Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "${STAGING_BRANCH}" ]; then
              echo "Updating staging environment..."
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git $STAGING_BRANCH:master
            fi

